---
name: cmpsc-100-fall-2018-practical4
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        practicalfour/MadLibs.java:
            --single 6 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 14
            --fragment "new Date(" --count 1 --exact
# --> check the number of commits beyond a threshold
--commits 12
# --> check that the program executes and produces 4 lines of output
# --> check that the output contains a fragment
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 15 --exact
--command "gradle -q --console plain run" --fragment "glitzy" --count 2 --exact
